import { LocalSvelteComponent } from "./shared";

export interface IIconProps {
  color?: "white"
  | "black-75"
  | "mineral-10"
  | "mineral-20"
  | "mineral-30"
  | "mineral-40"
  | "mineral-60"
  | "mineral-70"
  | "mineral-80"
  | "mineral-90"
  | "teal-40"
  | "teal-60"
  | "teal-70"
  | "purple-40"
  | "purple-60"
  | "purple-70",
  type?: "arrow-down"
  | "arrow-left"
  | "arrow-right"
  | "arrow-top"
  | "calendar"
  | "coin"
  | "collapse-closed"
  | "collapse-open"
  | "check"
  | "dropdown-closed"
  | "dropdown-open"
  | "edit"
  | "eye-closed"
  | "eye-opened"
  | "track"
  | "key"
  | "logout"
  | "lupe"
  | "minus"
  | "plus"
  | "reload"
  | "remove"
  | "sort"
  | "star"
  | "trash"
  | "upload"
  | "arrow-fill-right"
  | "arrow-fill-left"
  | "chevron-right"
  | "chevron-left"
  | "menu-expand"
  | "menu-collapse"
  | "menu-default"
  | "external"
  | "wallet"
  | "workspace",
  size?: "small" | "petit",
}

declare class Icon extends LocalSvelteComponent<IIconProps> {}
export default Icon;
